AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  People:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSXrayWriteOnlyAccess
      Handler: dist/handler/people
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /people
            Method: get
  Person:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSXrayWriteOnlyAccess
      Handler: dist/handler/person
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /person/{id}
            Method: get
  GetAllResourceKeys:
    Type: AWS::Serverless::Function
    Environment:
      Variables:
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
    Properties:
      Policies:
        - AWSXrayWriteOnlyAccess
      Handler: dist/handler/GetResourceKeys
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /media/projects/{projectID}/resources/{resourceID}/resourcekeys
            Method: get
  GetUploadUrl:
    Type: AWS::Serverless::Function
    Environment:
      Variables:
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
    Properties:
      Policies:
        - AWSXrayWriteOnlyAccess
      Handler: dist/handler/GetUploadUrls
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /media/projects/{projectID}/resources/{resourceID}
            Method: get
  DeleteResourceKeys:
    Type: AWS::Serverless::Function
    Environment:
      Variables:
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
    Properties:
      Policies:
        - AWSXrayWriteOnlyAccess
      Handler: dist/handler/DeleteResourceKeys
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /media/projects/{projectID}/resources/{resourceID}
            Method: delete
  Bucket1:
    Type: AWS::S3::Bucket
Outputs:
  URL:
    Description: URL for HTTPS Endpoint
    Value:
      Fn::Join:
        - ''
        - - https://
          - Ref: ServerlessRestApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/"
          - Ref: ServerlessRestApiProdStage
